#!/bin/bash

mount -o rw,remount /
location=/config/usb_gadget/g1/functions/  #loc of usb_gadget functions folder

mass_storage_name=$(ls $location | grep mass_storage)  #find mass_storage.* folder 

location_mass=$location/$mass_storage_name  #find in mass_storage folder
location=$location/$mass_storage_name/lun.0  #find lun.0 file in mass_storage folder

usb_controller=$(getprop sys.usb.controller)

gadget_path=/config/usb_gadget/g1  #gadget path my be g1,g2,g3 in other phone model

gadget_path_config=$gadget_path/configs/b.1 #config file of gadget where to mount the mass_storage

usb_mode_file=UDC

# echo "" > $gadget_path/$usb_mode_file

changeUsbMode(){
    # if [[ $1 == "off" ]];then
        echo "" > $gadget_path/$usb_mode_file 2> /dev/null
        sleep 3
    # else
        # echo "on"
        echo $usb_controller > $gadget_path/$usb_mode_file 2> /dev/null

        isEnabled=$(cat $gadget_path/$usb_mode_file)

        if [[ $isEnabled == $usb_controller ]];then
            echo "USB is enabled"
        else 
            echo "USB is disabled,run the script again"
        fi
    # # fi
}

changeMassStorageMode(){
    if [[ $1 == "on" ]];then
        rm $gadget_path_config/$mass_storage_name 2> /dev/null
        ln -s $location_mass $gadget_path_config/$mass_storage_name 2> /dev/null
        echo "Mass storage is enabled"
    else 
        rm $gadget_path_config/$mass_storage_name 2> /dev/null
        echo "Mass storage is disabled"
    fi
}

setReadWrite(){
    echo $1 > $location/ro 2> /dev/null
}


setCdrom(){
    echo $1 > $location/cdrom 2> /dev/null
}

setFile(){
    echo $1 > $location/file 2> /dev/null
}

print(){
    msg=$(cat $location/$1)
    echo "ISO=> "$msg
}

read(){
    if [ -z "$1" ] 
    then
        echo "Please input the iso file.."
    else
        setReadWrite 1
        setCdrom 0
        setFile $1
        changeMassStorageMode on
        # setprop sys.usb.config mass_storage
        changeUsbMode
        print file
    fi
}


 write(){
    if [ -z "$1" ];then
        echo "Please input the iso file.."
    else
        setReadWrite 0
        setCdrom 0
        setFile $1
        changeMassStorageMode on
        # setprop sys.usb.config mass_storage
        changeUsbMode
        print file
    fi
 }

 floppy(){
    if [ -z "$1" ];then
        echo "Please input the iso file.."
    else
        setReadWrite 1
        setCdrom 1
        setFile $1
        changeMassStorageMode on
        # setprop sys.usb.config mass_storage
        changeUsbMode
        print file
    fi
 }

  off(){
        setReadWrite 0
        setCdrom 0
        # setFile ""
        changeMassStorageMode off
        # setprop sys.usb.config mtp
        # changeUsbMode
  }

 execute(){
    file=$2
    case $1 in

    read|0)
    read $file
    ;;
    write|1)
    write $file 
    ;;
    floppy|2)
    floppy $file 
    ;;
    off)
    off 
    ;;
    --help|-h) 
    echo "./mounter  file.iso "
    # echo "./mounter read(0)|write(1)|floppy(2)   file.iso"
    echo "./mounter  file.iso #for write default"
    echo "example:  ./mounter write /sdcard/ubuntu.iso"
    echo "example:  ./mounter  write /sdcard/ubuntu.iso"
    ;;
    *)
    read $1
    ;;
    esac
}
execute $1 $2